# -*- coding: utf-8 -*-
# Generated by Django 2.0.5 on 2018-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20180603_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='dateStr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newsdata',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
