# Generated by Django 2.0.5 on 2018-06-08 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20180608_0051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisdata',
            options={'verbose_name_plural': 'Analysis Data'},
        ),
        migrations.AlterModelOptions(
            name='newsdata',
            options={'verbose_name_plural': 'News Data'},
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toCHN',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toJPN',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toKOR',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toPRK',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toTWN',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toUSA',
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='toID',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='toNews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.newsData'),
        ),
        migrations.AlterField(
            model_name='analysisdata',
            name='toCountry',
            field=models.BooleanField(default=False),
        ),
    ]
