# Generated by Django 2.0.5 on 2018-06-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20180608_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
