# Generated by Django 2.0.5 on 2018-06-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20180608_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='tocountrydata',
            name='toNation',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
