# Generated by Django 2.0.5 on 2018-06-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_delete_collecteddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='collectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromCountry', models.CharField(max_length=3)),
                ('num_news', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True, db_index=True, null=True)),
                ('toCountry', models.CharField(max_length=3)),
                ('toCheck', models.BooleanField(default=False)),
                ('toID', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Collected Data',
            },
        ),
    ]
