# Generated by Django 2.0.5 on 2018-06-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20180609_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collecteddata',
            options={'verbose_name_plural': 'Collected Data'},
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='num_news',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='toCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='toCountry',
            field=models.CharField(default='USA', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='toID',
            field=models.CharField(default=555, max_length=200),
            preserve_default=False,
        ),
    ]
