# Generated by Django 2.0.4 on 2018-06-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_remove_newsdata_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='freqList',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
