# Generated by Django 2.0.4 on 2018-06-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_auto_20180614_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='freqList',
            field=models.TextField(blank=True, null=True),
        ),
    ]
