# Generated by Django 2.0.6 on 2018-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_auto_20180620_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='sumcompound',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
