# Generated by Django 2.0.6 on 2018-06-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0035_auto_20180620_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='article',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
