# -*- coding: utf-8 -*-
# Generated by Django 2.0.5 on 2018-06-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
