# -*- coding: utf-8 -*-
# Generated by Django 2.0.5 on 2018-06-04 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='newsdata',
            name='url',
        ),
    ]
