# -*- coding: utf-8 -*-
# Generated by Django 2.0.5 on 2018-06-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20180604_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='compound',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
