# Generated by Django 2.0.5 on 2018-06-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20180606_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
