# Generated by Django 2.0.5 on 2018-06-08 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_newsdata_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='analysisData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('toCountry', models.CharField(blank=True, max_length=200, null=True)),
                ('toUSA', models.BooleanField(default=False)),
                ('toCHN', models.BooleanField(default=False)),
                ('toKOR', models.BooleanField(default=False)),
                ('toPRK', models.BooleanField(default=False)),
                ('toJPN', models.BooleanField(default=False)),
                ('toTWN', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='compound',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
