# Generated by Django 2.0.5 on 2018-06-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20180608_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
