# Generated by Django 2.0.5 on 2018-06-08 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20180608_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, null=True),
        ),
    ]
