# Generated by Django 2.0.5 on 2018-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20180608_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
