# Generated by Django 2.0.5 on 2018-06-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20180608_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='toCountryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toCheck', models.BooleanField(default=False)),
                ('toID', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toID',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toCountry',
        ),
        migrations.AddField(
            model_name='analysisdata',
            name='toCountry',
            field=models.ManyToManyField(to='services.toCountryData'),
        ),
    ]
