# Generated by Django 2.0.5 on 2018-06-09 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20180608_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='collectedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=3)),
                ('num_news', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Collected Data',
            },
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toCountry',
        ),
        migrations.RemoveField(
            model_name='analysisdata',
            name='toNews',
        ),
        migrations.AlterModelOptions(
            name='tocountrydata',
            options={'verbose_name_plural': 'toCountry Data'},
        ),
        migrations.DeleteModel(
            name='analysisData',
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='toCountry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.toCountryData'),
        ),
    ]
