# Generated by Django 2.0.5 on 2018-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_tocountrydata_tonation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collecteddata',
            old_name='country',
            new_name='fromCountry',
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='toCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collecteddata',
            name='toID',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collecteddata',
            name='toCountry',
            field=models.CharField(max_length=3),
        ),
        migrations.DeleteModel(
            name='toCountryData',
        ),
    ]
