# Generated by Django 2.0.5 on 2018-06-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20180608_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='collecteddata',
            name='date',
            field=models.DateField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
