# Generated by Django 2.0.5 on 2018-06-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_collecteddata_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='collectedData',
        ),
    ]
