# Generated by Django 2.0.4 on 2018-06-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_auto_20180613_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='freqList',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
