# Generated by Django 2.0.4 on 2018-06-14 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_auto_20180614_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='content',
        ),
    ]
