# Generated by Django 2.0.4 on 2018-06-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20180614_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdata',
            name='freqList',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
