# Generated by Django 2.0.6 on 2018-06-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_auto_20180614_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='toID',
            field=models.CharField(max_length=2000),
        ),
    ]
