# Generated by Django 2.0.6 on 2018-06-18 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_auto_20180617_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collecteddata',
            name='date',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
