# Generated by Django 2.0.6 on 2018-06-23 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_newsdata_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsdata',
            old_name='article',
            new_name='isArticle',
        ),
    ]
